project_root_directory/api_user/urls.py
"""
URL mappings for the user API.
"""

from django.urls import path

from api_user import views

app_name = 'api_user'

urlpatterns = [
    path('create/', views.CreateUserView.as_view(), name='create'),
    path('token/', views.CreateTokenView.as_view(), name='token'),
    path('me/', views.ManageUserView.as_view(), name='me')
]

project_root_directory/app_account/urls.py
"""
URL mappings for the app_account app.
"""
from django.urls import path

from app_account import views

app_name = 'app_account'

urlpatterns = [
    path('login/', views.view_login, name='login'),
    path('register/', views.register, name='register'),
    path('logout/', views.logout, name='logout'),
]

project_root_directory/project_folder/urls.py
from drf_spectacular.views import (
    SpectacularAPIView,
    SpectacularSwaggerView,
)
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('api/schema/', SpectacularAPIView.as_view(), name='api-schema'),
    path(
        'api/docs/',
        SpectacularSwaggerView.as_view(url_name='api-schema'),
        name='api-docs',
    ),
    path('api/user/', include('api_user.urls')),
    path('api/embeddings/', include('api_embeddings.urls')),
    path('accounts/', include('app_account.urls')),
    path('', include('app_chatbot.urls')),
]

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL,
        document_root=settings.MEDIA_ROOT,
    )

project_root_directory/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
    {% block styles %}{% endblock %}
    </head>
<body>
    <main>
        {% block content %}
        {% endblock %}
    </main>
    {% block scripts %}{% endblock %}
    </body>
</html>

project_root_directory/templates/dtl_chatbot.html
{% extends 'base.html' %}

{% block styles %}
<style>
    body,
    html {
        height: 100%;
        background-color: #212121;
        /* Dark background */
        font-family: 'Roboto', sans-serif;
        color: #ddd;
        /* Light text */
    }

    .messages-box {
        flex: 1;
        overflow-y: auto;
        background-color: #333;
        /* Darker background for messages */
        padding: 20px;
    }

    .messages-list {
        padding-left: 0;
        margin: 0;
        list-style: none;
    }

    .message {
        margin-bottom: 15px;
    }

    .message-text {
        padding: 10px;
        border-radius: 5px;
    }

    .sent {
        background-color: #444;
        /* Darker background for sent messages */
        align-self: flex-end;
    }

    .received {
        background-color: #555;
        /* Darker background for received messages */
        align-self: flex-start;
    }

    .message-form {
        display: flex;
        position: fixed;
        bottom: 0;
        left: 0;
        right: 0;
        padding: 10px;
        background-color: #333;
        /* Dark background for message form */
    }

    .message-input {
        flex: 1;
        border-radius: 4px;
        border: 1px solid #555;
        /* Darker border */
        padding: 10px;
        font-size: 16px;
        margin-right: 10px;
        background-color: #444;
        /* Darker input background */
        color: #ddd;
        /* Lighter text */
    }

    .card-header {
        background-color: #444
    }

    .btn-send {
        border-radius: 4px;
        background-color: #444;
        /* Primary button color */
        color: white;
        font-weight: bold;
        border: none;
        padding: 10px 20px;
        cursor: pointer;
        transition: background-color 0.3s;
    }

    .btn-send:hover {
        background-color: #555;
        /* Darker hover color */
    }

    .chat-container {
        height: 100%;
        display: flex;
        flex-direction: column;
    }
</style>
{% endblock %}


{% block content %}
<div class="chat-container">
    <div class="card flex-grow-1">
        <div class="card-header text-white">Chat</div>
        {% if user.is_authenticated %}
        <div class="card-header text-white"><b>Welcome, {{user.email}}</b> <a style="color: #999;"
                href="{% url 'app_account:logout' %}">Logout</a></div>
        {% else %}
        <div class="card-header bg-primary text-white"><a style="color: yellow" href="{% url 'app_account:login' %}">Login</a> <a
                style="color: yellow;" href="{% url 'app_account:register' %}">Register</a></div>
        {% endif %}
        <div class="card-body messages-box">

            <ul class="list-unstyled messages-list">

                <li class="message received">
                    <div class="message-text">
                        <div class="message-sender">
                            <b>AI Chatbot</b>
                        </div>
                        <div class="message-content">
                            Hi {{user.email}}, I am your AI Chatbot, you can ask me anything.
                        </div>
                    </div>
                </li>

                {% for chat in chats %}
                {% if chat.user == request.user %}

                <li class="message sent">
                    <div class="message-text">
                        <div class="message-sender">
                            <b>You</b>
                        </div>
                        <div class="message-content">
                            {{chat.message}}
                        </div>
                    </div>
                </li>

                <li class="message received">
                    <div class="message-text">
                        <div class="message-sender">
                            <b>AI Chatbot</b>
                        </div>
                        <div class="message-content">
                            {{chat.response}}
                        </div>
                    </div>
                </li>

                {% endif %}
                {% endfor %}

            </ul>

        </div>
    </div>
    <form class="message-form">
        {%csrf_token%}
        <div class="input-group">
            <input type="text" class="form-control message-input" placeholder="Type your message...">
            <div class="input-group-append">
                <button type="submit" class="btn btn-send">Send</button>
            </div>
        </div>
    </form>
</div>

<script>
    const messagesList = document.querySelector('.messages-list');
    const messageForm = document.querySelector('.message-form');
    const messageInput = document.querySelector('.message-input');

    messageForm.addEventListener('submit', (event) => {
        event.preventDefault();

        const message = messageInput.value.trim();
        if (message.length === 0) {
            return;
        }

        const messageItem = document.createElement('li');
        messageItem.classList.add('message', 'sent');
        messageItem.innerHTML = `
            <div class="message-text">
                <div class="message-sender">
                    <b>You</b>
                </div>
                <div class="message-content">
                    ${message}
                </div>
            </div>`;
        messagesList.appendChild(messageItem);

        messageInput.value = '';

        fetch('', {
            method: 'POST',
            headers: { 'Content-Type': 'application/x-www-form-urlencoded' },
            body: new URLSearchParams({
                'csrfmiddlewaretoken': document.querySelector('[name=csrfmiddlewaretoken]').value,
                'message': message
            })
        })
            .then(response => response.json())
            .then(data => {
                const response = data.response;
                const messageItem = document.createElement('li');
                messageItem.classList.add('message', 'received');
                messageItem.innerHTML = `
                <div class="message-text">
                    <div class="message-sender">
                        <b>AI Chatbot</b>
                    </div>
                    <div class="message-content">
                        ${response}
                    </div>
                </div>
                `;
                messagesList.appendChild(messageItem);
            });
    });

</script>
{% endblock %}

project_root_directory/templates/embed.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Embedding Generator</title>
</head>

<body>
    <h1>Generate Text Embedding</h1>
    <form method="post">
        {% csrf_token %}
        <textarea name="text" rows="4" cols="50"></textarea><br />
        <button type="submit">Generate Embedding</button>
    </form>
    <h2>Original</h2>
    {% if text %}
        {{ text }}
    {% endif %}
    <h2>Most Similar</h2>
    {% if result %}
        {{ result.document }}
    {% endif %}
    <h2>Embeddings in DB</h2>
    {% if embeddings %}
        {% for embedding in embeddings %} 
            {{ embedding.document }}
            <br>
            <!-- <pre>{{ embedding.embedding }}</pre> -->
        {% endfor %}
    {% endif %}
</body>

</html>

project_root_directory/templates/react_chatbot.html
{% extends "base.html" %}
{% load static %}

{% block title %}
    AI Chatbot
{% endblock %}

{% block styles %}
    <!-- Include any additional styles if necessary -->
    {% if main_css %}
        <link rel="stylesheet" href="{{ main_css }}">
    {% endif %}
{% endblock %}

{% block content %}
    <div id="root"></div>
{% endblock %}

{% block scripts %}
    <!-- Include any additional scripts if necessary before main_js -->
    {{ chats|json_script:'chats' }}

    <!-- Include React build script -->
    {% if main_js %}
        <script src="{{ main_js }}"></script> 
    {% endif %}
{% endblock %}